
file:
    upload-dir: C:\Users\joaquin\Desktop\archivos_spring
spring:
    servlet:
        multipart:
          enabled: true
          file-size-threshold: 2KB
          max-file-size: 10MB
          max-request-size: 10MB
    datasource:
      url: jdbc:mysql://localhost:3306/challange22122020?useSSL=false&serverTimezone=UTC
      #  url: jdbc:mysql://sqtfb802eq9uwos6:e5b85lcvikvq71r3@jhdjjtqo9w5bzq2t.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/sfpt5j9hav2axboi
      username: root
      # username: sqtfb802eq9uwos6
      #password: e5b85lcvikvq71r3
      password: a
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect